config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: [:create]
    end
  end

  post 'users/:user_id/posts', to: 'posts#create', as: 'posts'
  post 'users/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'likes'

  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.is? :default
      can :read, :all
      can :create, Comment
      can :destroy, Comment, user_id: user.id
      can :manage, Post, user_id: user.id
      can :manage, Like, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def short_text
    text.truncate(75)
  end

  def liked?(user)
    likes.where(user_id: user.id).any?
  end

  after_save :update_post_counter

  private

  def update_post_counter
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :likes
  has_many :comments

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_create do
    self.posts_counter = 0
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  ROLES = %i[admin default].freeze

  def admin?
    is? :admin
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  skip_before_action :verify_authenticity_token
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = 'Comment created!'
    else
      flash[:error] = 'Comment not created!'
    end
    redirect_to user_post_path(current_user, @post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment deleted!'
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    return if @post.liked?(current_user)

    @like = Like.new(user_id: current_user.id, post_id: @post.id)

    if @like.save
      flash[:success] = 'Liked!'
    else
      flash[:error] = 'ERROR!'
    end
    redirect_to user_post_path(current_user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to user_post_path(@user, @post)
    else
      flash[:error] = 'Post not created!'
      redirect_to "/users/#{@user.id}/posts/new"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted!'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render 'users/user' %>

<div class="user-posts">
  <% @user.posts.each do |post| %>
  <div class="user-bio black-border">
    <%= link_to post.title, user_post_path(user_id: @user.id, id: post.id), class: 'section-title' %>
    <p><%= post.short_text %></p>
    <p class="post-counters">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %> </p>
  </div>

  <ul class="post-comments black-border">
<% post.recent_comments.includes([:user]).each do |comment| %>
    <li class="comment"><%= comment.user.name %>: <%= comment.text %></li>
    <% end %>
  </ul>
  <% end %>
  <button>Show more</button>
</div>

app/views/posts/new.html.erb
<% flash.each do |type, msg| %>
<%= content_tag :div, msg, class: "#{type} alert" %>
<% end %>
<div class="new-post-container">
<h2 class="new-post-label">Create a new post:</h2>
<%= form_with url: "/users/#{@user.id}/posts", scope: :post, class: 'new-post-form' do |form| %>
      <%= form.text_field :title, placeholder: 'Title', class: 'new-post-title' %>
      <%= form.text_area :text, placeholder: 'Write your post here', class: 'new-post-text' %>
      <%= form.submit "Submit", class: 'new-post-btn' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "#{type} alert" %>
<% end %>
<div class="post black-border">
  <div class="post-detailed">
    <h3> <%= @post.title %> by <%= @user.name %></h3>
    <p>Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
  </div>
  <p><%= @post.text %></p>
  <%= form_with url: "#{@post.id}/likes", method: :post do |form| %>
    <%= form.submit "Like", class: 'like-btn' %>
  <% end %>
  <% if can? :destroy, @post %>
    <%= button_to 'Delete', user_post_path(@user, @post), method: :delete, class: 'delete black-border' %>
  <% end %>
  <div>
    <%= form_with url: "#{@post.id}/comments", scope: :comment, method: :post, class: 'comment-form' do |form| %>
      <%= form.text_area :text, placeholder: 'Write a comment...', required: true, class: 'comment-txt' %>
      <%= form.submit "Add comment", class: 'comment-btn' %>
    <% end %>
  </div>
</div>
<ul class="post-comments black-border">
  <% @post.comments.each do |comment| %>
    <li class="comment">
      <%= comment.user.name %>: <%= comment.text %>
      <% if can? :destroy, comment %>
        <%= button_to 'Delete', user_post_comment_path(comment.user, @post, comment ), method: :delete, class: 'delete black-border' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/_user.html.erb
<div class='user'>
  <img class="user-image black-border" src=<%=@user.photo%> alt='user-photo'>
  <div class="user-data black-border">
    <%= link_to @user.name, user_path(id: @user.id), class: 'user-name' %>
    <p class="user-posts">Posts: <%= @user.posts_counter || 0 %></p>
  </div>
</div>
<div class="post-btn-container">
  <%= link_to 'New Post', new_user_post_path(user_id: @user.id), class: 'new-post-btn' %>
</div>

app/views/users/index.html.erb
  <%= button_to(
  "Log Out",
  destroy_user_session_path,
  method: :delete
) %>
<% @users.each do |user| %>
  <div class='user'>
    <img class="user-image black-border" src='<%= user.photo %>' alt='user-photo'>
    <div class="user-data black-border">
      <p>
        <%= link_to user.name, user_path(id: user.id), class: 'user-name' %>
      </p>
      <p class="user-posts">Posts: <%= user.posts_counter || 0 %></p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'users/user' %>

<div class='user-bio black-border'>
  <p>Bio: <%= @user.bio %></p>
</div>

<div class="user-posts">
  <% @user.recent_posts.each do |post| %>
  <div class="user-bio black-border">
    <%= link_to post.title, user_post_path(user_id: @user.id, id: post.id), class: 'section-title' %>
    <p><%= post.short_text %></p>
    <p class="post-counters">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></p>
  </div>
  <% end %>
</div>

<%= link_to 'See all posts', user_posts_path(user_id: @user.id), class: 'btn-container posts-btn black-border' %>